# Generated by Django 5.2.5 on 2025-08-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('deadline_date', models.DateField()),
                ('reference_link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('renewed', 'Renewed'), ('expired', 'Expired'), ('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('related_system', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('renewed', 'Renewed'), ('expired', 'Expired'), ('pending', 'Pending'), ('resolved', 'Resolved')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VendorVPN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('renewed', 'Renewed'), ('expired', 'Expired'), ('pending', 'Pending'), ('resolved', 'Resolved')], default='active', max_length=10)),
            ],
        ),
    ]
